apiVersion: v2
name: external-dns-crds
description: A Helm chart to deploy the DNSEndpoint CRD
type: application
sources:
  - https://github.com/kubernetes-sigs/external-dns

version: 0.20.0

# renovate: datasource=github-releases depName=kubernetes-sigs/external-dns
appVersion: 0.20.0

maintainers:
  - name: morremeyer
