apiVersion: v2
name: system-upgrade-controller-crds
description: A Helm chart to deploy the system-upgrade-controller CRDs
type: application
sources:
  - https://github.com/rancher/system-upgrade-controller

# renovate: datasource=github-releases depName=rancher/system-upgrade-controller
version: 0.20.0

# renovate: datasource=github-releases depName=rancher/system-upgrade-controller
appVersion: 0.19.0

maintainers:
  - name: ekeih
